name: Git commit
description: Create a commit in a git repository
inputs:
  commit_message:
    description: the commit message for any changes made by former actions
    required: true
  pattern:
    description: the pattern to use with git add
    required: true
runs:
  using: node12
  main: dist/index.js
