name: Tag and commit
description: Create a tag and commits changes to the git repository
inputs:
  is_release_candidate:
    description: true/false determining if this is a release candidate (new deploy) or not
    required: true
  commit_message:
    description: the commit message for any changes made by former actions
    required: true
  tag_message:
    description: the tag message for this release.
    required: false
  pattern:
    description: the pattern to use with git add
    required: false
    default: "."
runs:
  using: node12
  main: dist/index.js
