name: Cucumber integration with JVM
description: Checks out bidrag-cucumber-backend to runner workspace and runs integration tests, will delete existing bidrag-dokument-backend folder
runs:
  using: node12
  main: dist/index.js
inputs:
  cucumber_tag:
    description: The cucumber tag to use when running integration tests suite
    required: false
  do_not_fail:
    description: The cucumber integration test suite should not cause a workflow failure when tests have errors
    required: true
    default: "false"
  github_project:
    description: The name of the cucumber github project
    required: true
    default: bidrag-cucumber-backend
  maven_command:
    description: The command used to run tests with maven
    required: true
    default: test
  optional_maven_command:
    description: An optional maven command
    required: false
  relative_json_path:
    description: inputs containing evironment, username for test user, relative nais_project_folder, and azure credentials for apps secured with azure
    required: true
    default: json/integrationInput.json
  username:
    description: The nav user which will be used to set up security for the integration tests (only required for tests with ISSO-token)
    required: false
