name: Cucumber integration with JVM
description: Checks out bidrag-cucumber-backend to runner workspace and runs integration tests, will delete existing bidrag-dokument-backend folder
runs:
  using: node12
  main: dist/index.js
inputs:
  cucumber_tag:
    description: The cucumber tag to use when running integration tests suite
    required: false
  do_not_fail:
    description: The cucumber integration test suite should not cause a workflow failure when tests have errors
    required: true
    default: "false"
  github_project:
    description: The name of the cucumber github project
    required: true
    default: bidrag-cucumber-backend
  maven_command:
    description: The command used to run tests with maven
    required: true
    default: test
  optional_maven_command:
    description: An optional maven command
    required: false
  maven_image:
    description: The image containing maven and java version to use for running the integration tests.
    required: true
  pip_user:
    description: The server user which is used in bidrag-sak
    required: false
  test_user:
    description: The test user which will be used running the scenarios in the integration tests
    required: true
  username:
    description: The nav user which will be used to set up security for the integration tests
    required: true
