name: Cucumber Integration Test execution
description: Execute cucumber integration running tests running on a jvm for team bidrag
inputs:
  cucumber_tags:
    description: the tagged tests to run
    required: true
  maven_image:
    description: the docker maven image to use containing maven and java version
    required: true
  environment:
    description: the environment where the test will run, for instance q0
    required: true
  github_repository:
    description: name of the cucumber project to run, hosted on github/navikt
    required: false
    default: bidrag-cucumber-backend
runs:
  using: node12
  main: dist/index.js
