name: Cucumber integration with JVM
description: Checks out bidrag-cucumber-backend to runner workspace and runs integration tests, will delete existing bidrag-dokument-backend folder
runs:
  using: node12
  main: dist/index.js
inputs:
  maven_image:
    description: The image containing maven and java version to use for running the integration tests.
    required: true
  cucumber_tag:
    description: The cucumber tag to use when running integration tests suite
    required: true
