name: build actions
on:
  push:
    branches:
      - 'ignore'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '13.x'
      - run: npm i -g @zeit/ncc
      - name: Debug workspace
        run: env
      - name: Install setup
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: bidrag-maven/setup
      - name: Install verify-dependencies
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: bidrag-maven/verify-dependencies
      - name: Generate timestamp
        id: now
        run: echo ::set-output name=timestamp::$(date +"%Y-%m-%d:%T")
      - uses: navikt/bidrag-git/commit@v5
        with:
          commit_message: "${{ steps.now.outputs.timestamp }}: Build of actions with npm and ncc"
          pattern: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
