name: build actions
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-16.04
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i -g @zeit/ncc
      - name: Debug workspace
        run: env
      - name: Install build-node-artifact
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/build-node-artifact
      - name: Install git-commit
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/git-commit
      - name: Install git-tag
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/git-tag
      - name: Install git-tag-n-commit-mvn-deploy
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/git-tag-n-commit-mvn-deploy
      - name: Install maven-build
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/maven-build
      - name: Install maven-cucumber
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/maven-cucumber
      - name: Install maven-setup
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/maven-setup
      - name: Install maven-verify-dependencies
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/maven-verify-dependencies
      - name: Install release-mvn-pkg
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/release-mvn-pkg
      - name: Install release-prepare-mvn-pkg
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/release-prepare-mvn-pkg
      - name: Install release-verify-auto-deploy
        uses: navikt/bidrag-actions/build-node-artifact@master
        with:
          artifact_folder: bidrag-actions/release-verify-auto-deploy
      - run: date +"%Y-%m-%d:%T" > .build-date
      - name: Commit ncc build in bidrag-actions
        uses: navikt/bidrag-actions/git-commit@master
        with:
          commit_message: "{}: Fresh build of actions with npm and ncc"
          commit_message_file: .build-date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
